[[main]]
  name = "Self Introduction"
  url = "self_introduction/"
  weight = 20

[[main]]
  name = "Contact"
  url = "contact/"
  weight = 20

[[main]]
  name = "Publication"
  url = "publication/"
  weight = 20
  
[languages]
  [languages.en]
    weight = 1
    contentDir = "content/en"
    # languageDirection = 'rtl' for Right-To-Left languages

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 3



